<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>FloatingHelper.Plugins.SaveToFile</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FloatingHelper.Core\FloatingHelper.Core.csproj" />
  </ItemGroup>

</Project>
